<a href="https://colab.research.google.com/github/Uday-1402/ML_Learn/blob/main/data_gathering_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Just setting up google colab to download datasets from kaggle

In [4]:
import os

os.makedirs('/root/.kaggle', exist_ok=True)

# Replace with your actual username and API key
kaggle_config = {
    "username": "udayt14",
    "key": ""
}

import json
with open('/root/.kaggle/kaggle.json', 'w') as f:
    json.dump(kaggle_config, f)

os.chmod('/root/.kaggle/kaggle.json', 0o600)

In [3]:
!pip install kaggle

!kaggle datasets download -d <dataset-owner>/<dataset-name>
!unzip <dataset-name>.zip

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.1.4)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)
/bin/bash: -c: line 1: syntax error near unexpected token `newline'
/bin/bash: -c: line 1: `kaggle datasets download -d <dataset-owner>/<dataset-name>'
/bin/bash: line 1: dataset-name: No such file or directory

In [9]:
# The below command downloads and unzips the dataset.

In [5]:
!kaggle datasets download -d kaggle/recipe-ingredients-dataset
!unzip recipe-ingredients-dataset.zip

Dataset URL: https://www.kaggle.com/datasets/kaggle/recipe-ingredients-dataset
License(s): unknown
Downloading recipe-ingredients-dataset.zip to /content
  0% 0.00/2.23M [00:00<?, ?B/s]
100% 2.23M/2.23M [00:00<00:00, 782MB/s]
Archive:  recipe-ingredients-dataset.zip
  inflating: test.json
  inflating: train.json

# Working with JSON

In [1]:
import pandas as pd

In [6]:
df = pd.read_json('train.json')

In [7]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [8]:
!kaggle datasets download -d busielmorley/worldcities-pop-lang-rank-sql-create-tbls
!unzip worldcities-pop-lang-rank-sql-create-tbls.zip

Dataset URL: https://www.kaggle.com/datasets/busielmorley/worldcities-pop-lang-rank-sql-create-tbls
License(s): world-bank
Downloading worldcities-pop-lang-rank-sql-create-tbls.zip to /content
  0% 0.00/89.9k [00:00<?, ?B/s]
100% 89.9k/89.9k [00:00<00:00, 258MB/s]
Archive:  worldcities-pop-lang-rank-sql-create-tbls.zip
  inflating: world.sql

# Working with SQL

In [10]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 64.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-linux_x86_64.whl size=247950 sha256=5c7c664d09f9967e84b0c2fa9ab7dee5bd26cc32f824c51a1e657338927c99d2
  Stored in directory: /root/.cache/pip/wheels/03/17/fa/d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [11]:
import mysql.connector

In [16]:
# In the lecture he is using local setup of database using xampp and local jupyter notebook for this part.
# I also have that db set up locally but I am using google colab
# Google colab runs on cloud so it cannot directly access localhost
# So I used ngrok to expose my local mysql server. Hence the host name.
conn = mysql.connector.connect(host='0.tcp.in.ngrok.io',user='root',password='',database='world',port='17903')

In [20]:
df = pd.read_sql_query("select * from city where CountryCode like 'IND'",conn)

/tmp/ipython-input-618/3831303207.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("select * from city where CountryCode like 'IND'",conn)

In [21]:
df

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [22]:
!git config --global user.email "udayt1402@gmail.com"
!git config --global user.name "Uday-1402"

In [26]:
from google.colab import userdata

token = userdata.get('github_pat')

# Use it in your git remote URL
!git remote set-url origin https://{token}@github.com/Uday-1402/ML_Learn

fatal: not a git repository (or any of the parent directories): .git

# Working with APIs

In [27]:
import pandas as pd

In [28]:
import requests

In [30]:
response = requests.get("https://api.themoviedb.org/3/discover/movie?api_key=7ab284ec859efcd7a29ef82c737662b4")

In [45]:
df = pd.DataFrame()

In [47]:
dfs = []
for i in range(1,429):
  response = requests.get(f"https://api.themoviedb.org/3/discover/movie?api_key=7ab284ec859efcd7a29ef82c737662b4&page={i}")
  tmp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','popularity','overview','vote_average','vote_count']]
  dfs.append(tmp_df)
df = pd.concat(dfs,ignore_index=True)

In [48]:
df

,id,title,release_date,popularity,overview,vote_average,vote_count
0,1290821,Shelter,2026-01-28,543.5405,A man living in self-imposed exile on a remote...,6.792,180
1,799882,The Bluff,2026-02-17,390.8723,When her tranquil life on a remote island is s...,5.873,126
2,1199193,Pose,2026-02-25,281.4318,"Isolated in a grand country manor, a reclusive...",8.200,10
3,1159559,Scream 7,2026-02-25,239.3962,When a new Ghostface killer emerges in the qui...,5.997,171
4,680493,Return to Silent Hill,2026-01-21,228.6204,When James receives a mysterious letter from h...,5.045,221
...,...,...,...,...,...,...,...
8555,1504899,Recluse,,8.5214,Joan is a solitary audio engineer who returns ...,0.000,0
8556,486198,"Wo bleibst du, Baby?",2005-01-01,8.3703,,0.000,0
8557,271433,Wir sind die Neuen,2014-07-17,7.5784,Three old friends from college move back in to...,6.536,70
8558,890504,The Journey Away,1945-12-26,8.3142,Bernt comes to a small town to rob the bank. B...,1.000,2
8559,1064031,Let No Man Put Asunder,1921-07-18,9.1520,"During the 1200s, the catholic priest Peder ha...",0.000,0

In [49]:
df.shape()

TypeError: 'tuple' object is not callable

In [50]:
df.shape

(8560, 7)

In [51]:
df.to_csv('movies.csv')